## Aviation Safety Risk Analysis
** Authored by: Mr. Calvince Odhiambo**
** Date: 31/1/2026**
## Business Problem
Our company is considering entering the aviation industry but lacks knowledge about aircraft safety risks. This analysis uses historical aviation accident data to identify aircraft with lower operational risk.

In [9]:
#create a python cellinstalling required libraries
import pandas as pd

In [10]:
pip install pandas matplotlib seaborn

Requirement already satisfied: pandas in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (2.3.3)
Requirement already satisfied: matplotlib in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (3.9.4)
Requirement already satisfied: seaborn in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (0.13.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from matplotlib) (4.60.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: packaging>=20.0 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from matplotlib) (3.3.1)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: zipp>=3.1.0 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from importlib-resources>=3.2.0->matplotlib) (3.21.0)
Requirement already satisfied: six>=1.5 in c:\users\codhiambo\appdata\local\anaconda3\envs\learn-env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd

df = pd.read_csv("flight.csv", low_memory=False) #Load the data, read CSV file and turns it into a pandas DF.
df.head()
#I have"peeked" at the data and checked that loaded correctly, nature of column names, kind of data & problems.
# some of the column heads include accident date, airline operator, fatalities etc.

,Unnamed: 0,acc.date,type,reg,operator,fat,location,dmg
0,0,03-Jan-22,British Aerospace 4121 Jetstream 41,ZS-NRJ,SA Airlink,0,near Venetia Mine Airport,sub
1,1,04-Jan-22,British Aerospace 3101 Jetstream 31,HR-AYY,LANHSA - Línea Aérea Nacional de Honduras S.A,0,Roatán-Juan Manuel Gálvez International Airpor...,sub
2,2,05-Jan-22,Boeing 737-4H6,EP-CAP,Caspian Airlines,0,Isfahan-Shahid Beheshti Airport (IFN),sub
3,3,08-Jan-22,Tupolev Tu-204-100C,RA-64032,"Cainiao, opb Aviastar-TU",0,Hangzhou Xiaoshan International Airport (HGH),w/o
4,4,12-Jan-22,Beechcraft 200 Super King Air,NaN,private,0,"Machakilha, Toledo District, Grahem Creek area",w/o

In [12]:
#I want to see the last few rows
df.tail()

,Unnamed: 0,acc.date,type,reg,operator,fat,location,dmg
2495,1245,20-Dec-18,Cessna 560 Citation V,N188CW,Chen Aircrafts LLC,4,"2 km NE of Atlanta-Fulton County Airport, GA (...",w/o
2496,1246,22-Dec-18,PZL-Mielec M28 Skytruck,GNB-96107,Guardia Nacional Bolivariana de Venezuela - GNBV,0,Kamarata Airport (KTV),sub
2497,1247,24-Dec-18,Antonov An-26B,9T-TAB,Air Force of the Democratic Republic of the Congo,0,Beni Airport (BNC),w/o
2498,1248,31-Dec-18,Boeing 757-2B7 (WL),N938UW,American Airlines,0,"Charlotte-Douglas International Airport, NC (C...",sub
2499,1249,unk. date 2018,Rockwell Sabreliner 80,N337KL,private,0,"Eugene Airport, OR (EUG)",sub

## Data Understanding
The dataset contains aviation accident records from 1962 to 2023. It includes aircraft manufacturer, model, accident date, injury counts, and damage severity. Due to the long time span and reporting differences, several fields may contain missing values.

In [13]:
df.shape
# I can see we have 2500 rows and 8 colums

(2500, 8)

In [14]:
df.columns
# Viewing a list of all column names

Index(['Unnamed: 0', 'acc.date', 'type', 'reg', 'operator', 'fat', 'location',
       'dmg'],
      dtype='object')

In [15]:
# I need to seethe data types and missing values count. A very useful information of course
df.info()
# I can see that 'almost' no missing data in key columns as would have been expected of aviation data
# Small issues can be observed:1)Unnamed: 0 → useless → drop it (2)Dates are strings → convert to datetime (3)Fat (fatalities) is string → clean/convert to numeric if you want math (sum fatalities, average, etc.)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2500 non-null   int64
 1   acc.date    2500 non-null   object
 2   type        2500 non-null   object
 3   reg         2408 non-null   object
 4   operator    2486 non-null   object
 5   fat         2488 non-null   object
 6   location    2500 non-null   object
 7   dmg         2500 non-null   object
dtypes: int64(1), object(7)
memory usage: 156.4+ KB

In [16]:
df.describe()
#looking at the basic statistics for numeric columns - mean, std etc

        Unnamed: 0
count  2500.000000
mean    624.500000
std     360.915993
min       0.000000
25%     312.000000
50%     624.500000
75%     937.000000
max    1249.000000